# Day 29

```{r, message = FALSE}
library(tidyverse)
library(viridis)
library(mvnfast)
library(igraph)
library(Matrix)
library(patchwork)
library(rstan)
## use recommended rstan settings
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
library(bayesplot)

set.seed(101)
```


## Announcements

## Areal Data

- Areal data are data that are associated with a spatial region 
    - the actual data might have occured at point locations but are aggregated across space
    - example: disease spread
        - individuals either have a disease or don't (point level data) but the data are reported at aggregate levels (number of infections in the county/state/country)

    - some data are only meaninful at the area level: e.g., votes in a county/state

- areal data are models for discrete spatial domains (geostatistical models are for continuous spatial domains)

- partition the domain $\mathcal{D}$ into $n$ discrete units

- define $\mathbf{y} = (y_1, \ldots, y_n)'$

- spatial models: 
    - account for spatial autocorrelation between regions which improves the residual error model
    - borrows strength across locations to improve inference

- Question: how to measure the "closeness" of irregulary spaced regions?

    **draw figure here**
    
    - can use spatial centroid
    
    **draw figure here**
    
    - can I just use the geostatistical methods introduced previously?
    
        - geostatistical models produce a valid, positive definite covariance matrix
        
        - using continuous (geostatistical) methods works if the regions are rectangular shaped and of the same general size
    
    - can also model the covariance using adjacency matrices and graphical models
    
